services:
  - type: web
    name: bokpriser
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install chromium
    startCommand: gunicorn bokpriser:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
